name: pileline

on:
  - push
  - pull_request

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          distribution: 'ubuntu'
#
#      - name: Setup JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#
#      - name: Run Detekt linter
#        run: |
#          chmod +x ./gradlew
#          ./gradlew detekt
          

  unit-test:
#    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build --tag ft-app:latest .